# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98de01c41ceaeea00c3a9d2fc6e07c88c89f7f2e4fd799daf24e599c2f5bbba59d626902b7442f5ab2f5f8e86ac4a768267cf293f192c2ab5aa5b076912b9038

test:
  secret_key_base: 459be6f8ec9876cef15bfc9315168213ccdc64af6fe64385ae39df49f7b08599c0bb77de7ecda5116a28346835515bdbd4c7f2543ce6b8ef5bb050c4ea34cdac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
